### ISSUE TITLE
Typo in JavaScript component documentation

### ISSUE THREAD

**Issue by rafaucau** [flarum/api-docs#15]
After copying the code from the documentation, my code wouldn't work.
It turned out there is a typo: "compone"
For example. `import Modal from 'flarum/compone/Modal'` should be `import Modal from 'flarum/components/Modal'`
This typo applies to every component in the documentation.
Eg. https://api.docs.flarum.org/js/v0.1.0-beta.13/class/src/common/components/modal.js~modal

**Comment by datitisev** [comment]
Oh I think I know why 🤦.

https://github.com/flarum/api-docs/blob/4333c4489a083ea71cc98b7082d29e3709ba9ca1/esdoc.json#L37-L45

This seems to be a RegExp and not a string. `nts` is caught by `.ts` and replaced with nothing.

Thanks for the report!

**Comment by datitisev** [comment]
Fixed in https://github.com/flarum/api-docs/commit/cc75c982c91a06c4970fba19ea5860bf6ff5644b.
