### ISSUE TITLE
.tsx files not loaded

### ISSUE THREAD

**Issue by askvortsov1** [flarum/api-docs#16]
It doesn't seem to register `.tsx` files.

**Comment by datitisev** [comment]
It doesn't seem to be possible right now. There might be a plugin out there, but I cannot find one.

![image](https://user-images.githubusercontent.com/6401250/95639311-f5fe7200-0a65-11eb-8eeb-9a77e20a2120.png)

The ECMAScript proposals are already being used 🙃

**Comment by dsevillamartin** [comment]
looks to be working now
